"""Regenerate the embedded TACO seed from a local 4th-edition workbook.

Usage: python scripts/import-taco.py path/to/Taco-4a-Edicao.xlsx
The workbook is read only. Missing/NA values are omitted; Tr is kept as a
trace with no numeric amount. The generated SQL is applied once by migration 4.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from numbers import Real
import openpyxl

MAPPING = {
    3: ("energy_kcal", "kcal"),
    5: ("protein_g", "g"),
    6: ("fat_g", "g"),
    8: ("carbohydrate_g", "g"),
    9: ("fiber_g", "g"),
    11: ("calcium_mg", "mg"),
    12: ("magnesium_mg", "mg"),
    15: ("phosphorus_mg", "mg"),
    16: ("iron_mg", "mg"),
    17: ("sodium_mg", "mg"),
    18: ("potassium_mg", "mg"),
    20: ("zinc_mg", "mg"),
    23: ("vitamin_a_mcg_rae", "mcg"),
    24: ("vitamin_b1_mg", "mg"),
    25: ("vitamin_b2_mg", "mg"),
    26: ("vitamin_b6_mg", "mg"),
    27: ("vitamin_b3_mg", "mg"),
    28: ("vitamin_c_mg", "mg"),
}


def quote(value: object) -> str:
    return "'" + str(value).replace("'", "''") + "'"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("workbook", type=Path)
    args = parser.parse_args()
    target = Path(__file__).resolve().parents[1] / "src-tauri/migrations/0004_nutrition.sql"
    marker = "-- TACO_SEED_BEGIN (generated by scripts/import-taco.py)"
    schema = target.read_text(encoding="utf-8").split(marker)[0] + marker + "\n"
    sheet = openpyxl.load_workbook(args.workbook, read_only=True, data_only=True).worksheets[0]
    foods: list[str] = []
    nutrients: list[str] = []
    category = ""
    for row in sheet.iter_rows(min_row=4, values_only=True):
        number, name = row[0], row[1]
        if isinstance(number, str) and not name and number.strip() and number.strip() != "Número do":
            category = number.strip()
            continue
        if not isinstance(number, int) or not isinstance(name, str) or not name.strip():
            continue
        food_id = f"taco:{number}"
        foods.append(
            f"({quote(food_id)},'taco',{quote(number)},{quote(name.strip())},"
            f"{quote(category)},100,'g',1,0,'','2026-09-27T00:00:00Z','2026-09-27T00:00:00Z')"
        )
        for column, (key, unit) in MAPPING.items():
            value = row[column]
            if isinstance(value, Real) and not isinstance(value, bool) and value >= 0:
                nutrients.append(
                    f"({quote(food_id)},{quote(key)},{value:.6f},{quote(unit)},'measured')"
                )
            elif isinstance(value, str) and value.strip().lower() == "tr":
                nutrients.append(
                    f"({quote(food_id)},{quote(key)},NULL,{quote(unit)},'trace')"
                )
    if len(foods) != 597:
        raise ValueError(f"Expected 597 foods, got {len(foods)}")
    statements = [schema]
    for values, table, columns in [
        (foods, "foods", "id,source_id,source_item_id,name,category,base_amount,base_unit,edible_portion,is_custom,notes,created_at,updated_at"),
        (nutrients, "food_nutrients", "food_id,nutrient_key,amount,unit,qualifier"),
    ]:
        # Bounded batches keep the migration compatible with SQLite limits.
        for start in range(0, len(values), 250):
            statements.append(
                f"INSERT INTO {table}({columns}) VALUES\n" + ",\n".join(values[start : start + 250]) + ";\n"
            )
    target.write_text("\n".join(statements), encoding="utf-8")
    print(f"Generated {len(foods)} foods and {len(nutrients)} nutrient values")


if __name__ == "__main__":
    main()
